[release]
port = 8000
workers = 3
secret_key = "3eeb40bff050b8c8893dbba01b06349275cc34c31c50d607f6a416faf5198115"

[release.limits]
file = "5 MiB"

[default.databases]
mongodb_uri = "mongodb+srv://aslambhai93164_db_user:n5DlCVfjlXtzBv5i@mento0.6i4vpk2.mongodb.net/"